apiVersion: apps/v1
kind: Deployment
metadata:
    name: seedgpt
    namespace: seedgpt
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seedgpt
    template:
        metadata:
            labels:
                app: seedgpt
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: seedgpt
                    image: "SeedGPT/seedgpt:e52a54b5c03b3cdb0ac86a52a82fa37c1b35a638"
                    imagePullPolicy: Always
                    envFrom:
                        -   secretRef:
                                name: seedgpt-secrets
