apiVersion: apps/v1
kind: Deployment
metadata:
    name: seedgpt
    namespace: seedgpt
spec:
    replicas: 1
    selector:
        matchLabels:
            app: seedgpt
    template:
        metadata:
            labels:
                app: seedgpt
        spec:
            automountServiceAccountToken: false
            containers:
                -   name: seedgpt
                    image: "rhaversen/seedgpt:0eda0bfed2a02140bc6e70c1f5ede7098fb2f976"
                    imagePullPolicy: Always
                    envFrom:
                        -   secretRef:
                                name: seedgpt-secrets
